In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


In [8]:
prob=0.25
dropout=nn.Dropout(p=prob)
x=torch.ones(10)
y=dropout(x)
print(y)
print(torch.mean(y))


tensor([0.0000, 0.0000, 1.3333, 1.3333, 0.0000, 1.3333, 0.0000, 1.3333, 1.3333,
        1.3333])
tensor(0.8000)


In [9]:
dropout.eval()
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [10]:
dropout.eval()
y=F.dropout(x)
print(y)
print(torch.mean(y))

tensor([0., 0., 0., 0., 2., 0., 2., 2., 2., 0.])
tensor(0.8000)


In [12]:

y=F.dropout(x,training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [13]:
dropout.train()
y=dropout(x)
print(y)

tensor([1.3333, 0.0000, 1.3333, 1.3333, 1.3333, 1.3333, 1.3333, 1.3333, 1.3333,
        1.3333])


In [14]:
dropout.eval()
y=dropout(x)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [15]:
y=dropout(x)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
