In [2]:
import numpy as np
import torch
from torch.utils.data import DataLoader,TensorDataset
   

In [2]:
nObservation=100
nFeatures=20
data=np.random.randn(nObservation,nFeatures)

In [4]:
dataT=torch.tensor(data)
print('Numpy data: ')
print(type(data))
print(data.shape)
print(data.dtype)
print(" ")
print('Tensor data: ')
print(type(dataT))
print(dataT.size())
print(dataT.dtype)
print(" ")


Numpy data: 
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data: 
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [5]:
dataT2=torch.tensor(data).float()
print(dataT2.dtype)
dataT3=torch.tensor(data).long()
print(dataT3.dtype)


torch.float32
torch.int64


In [6]:
data

array([[ 2.13724249, -0.98929274, -1.59988395, ..., -0.17677822,
        -0.61371412, -0.48291322],
       [-0.34684815,  0.09451618,  0.94262529, ...,  0.89454348,
         1.10683191, -0.84756276],
       [-1.03116522,  1.30715015, -0.541918  , ..., -2.41950613,
        -0.6311794 ,  1.35544213],
       ...,
       [ 0.17528659, -1.00400465, -0.05493022, ..., -0.03029377,
         1.02614443,  0.29324848],
       [ 0.45237871,  0.1104014 ,  0.84256392, ..., -0.05447679,
        -1.61277477,  1.27523231],
       [-0.15781519,  0.99090453, -0.02633614, ...,  0.12683635,
        -0.13239377, -1.26673758]])

In [7]:
dataT2

tensor([[ 2.1372, -0.9893, -1.5999,  ..., -0.1768, -0.6137, -0.4829],
        [-0.3468,  0.0945,  0.9426,  ...,  0.8945,  1.1068, -0.8476],
        [-1.0312,  1.3072, -0.5419,  ..., -2.4195, -0.6312,  1.3554],
        ...,
        [ 0.1753, -1.0040, -0.0549,  ..., -0.0303,  1.0261,  0.2932],
        [ 0.4524,  0.1104,  0.8426,  ..., -0.0545, -1.6128,  1.2752],
        [-0.1578,  0.9909, -0.0263,  ...,  0.1268, -0.1324, -1.2667]])

In [8]:
dataT3

tensor([[ 2,  0, -1,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  1,  0],
        [-1,  1,  0,  ..., -2,  0,  1],
        ...,
        [ 0, -1,  0,  ...,  0,  1,  0],
        [ 0,  0,  0,  ...,  0, -1,  1],
        [ 0,  0,  0,  ...,  0,  0, -1]])

In [13]:
dataset=TensorDataset(dataT)
dataset.tensors

(tensor([[ 2.1372, -0.9893, -1.5999,  ..., -0.1768, -0.6137, -0.4829],
         [-0.3468,  0.0945,  0.9426,  ...,  0.8945,  1.1068, -0.8476],
         [-1.0312,  1.3072, -0.5419,  ..., -2.4195, -0.6312,  1.3554],
         ...,
         [ 0.1753, -1.0040, -0.0549,  ..., -0.0303,  1.0261,  0.2932],
         [ 0.4524,  0.1104,  0.8426,  ..., -0.0545, -1.6128,  1.2752],
         [-0.1578,  0.9909, -0.0263,  ...,  0.1268, -0.1324, -1.2667]],
        dtype=torch.float64),)

In [16]:
labels=torch.ceil(torch.linspace(0.01,4,nObservation))
labels=labels.reshape((len(labels),1))
# print(labels)
dataset=TensorDataset(dataT,labels)
print(dataset.tensors[0].size())
print(dataset.tensors[1].size())
print(np.shape(np.random.randint(5,size=nObservation)))

torch.Size([100, 20])
torch.Size([100, 1])
(100,)


In [18]:
batchsize=25
dataloader=DataLoader(dataset,batch_size=batchsize)
dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [20]:
for dat,labels in dataloader:
    print('BATCH INFO: ')
    print(dat.size())
    print(labels.size())
    print(' ')

BATCH INFO: 
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO: 
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO: 
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO: 
torch.Size([25, 20])
torch.Size([25, 1])
 


In [22]:
for dat,labs in dataloader:
    print(labs.T)
    print(' ')

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
 
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])
 
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3.]])
 
tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 4., 4., 4.]])
 


In [23]:
batchsize=25
dataloader=DataLoader(dataset,batch_size=batchsize,shuffle=True)
dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [24]:
for dat,labs in dataloader:
    print(labs.T)
    print(' ')

tensor([[3., 1., 1., 2., 1., 2., 2., 4., 3., 4., 2., 4., 4., 2., 1., 4., 2., 1.,
         3., 2., 2., 2., 2., 3., 1.]])
 
tensor([[3., 3., 4., 1., 1., 4., 2., 2., 2., 4., 1., 4., 2., 1., 4., 2., 1., 4.,
         4., 1., 1., 3., 3., 4., 1.]])
 
tensor([[2., 4., 1., 2., 4., 1., 4., 1., 2., 3., 3., 3., 2., 2., 3., 1., 4., 2.,
         4., 3., 4., 2., 3., 3., 2.]])
 
tensor([[4., 1., 3., 2., 1., 4., 4., 3., 2., 3., 3., 4., 3., 3., 1., 3., 3., 1.,
         4., 3., 1., 1., 4., 3., 1.]])
 


In [25]:
for dat,labs in dataloader:
    print(labs.T)
    print(' ')

tensor([[4., 2., 3., 4., 3., 1., 4., 2., 3., 1., 1., 3., 3., 4., 1., 2., 1., 1.,
         2., 2., 2., 1., 2., 4., 2.]])
 
tensor([[2., 4., 1., 3., 1., 3., 4., 3., 2., 4., 2., 1., 2., 4., 1., 2., 1., 1.,
         4., 1., 2., 4., 4., 3., 4.]])
 
tensor([[4., 3., 3., 1., 3., 1., 3., 4., 2., 4., 4., 2., 1., 2., 3., 2., 3., 1.,
         3., 3., 1., 4., 2., 1., 4.]])
 
tensor([[3., 4., 2., 2., 1., 3., 2., 4., 3., 2., 3., 1., 4., 3., 4., 1., 2., 3.,
         1., 3., 4., 4., 1., 2., 3.]])
 


In [26]:
dat,labs=next(iter(dataloader))
labs

tensor([[4.],
        [4.],
        [1.],
        [3.],
        [2.],
        [2.],
        [1.],
        [2.],
        [1.],
        [4.],
        [2.],
        [1.],
        [3.],
        [2.],
        [4.],
        [4.],
        [3.],
        [2.],
        [2.],
        [2.],
        [4.],
        [2.],
        [2.],
        [4.],
        [1.]])