In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
fakedata=np.tile(np.array([1,2,3,4]),(10,1))+np.tile(10*np.arange(1,11),(4,1)).T
fakelabels=np.arange(10)>4
print(fakedata)
print()
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]

[False False False False False  True  True  True  True  True]


In [6]:
partitons=[0.8,0.1,0.1]
X_train, X_TMPtest, y_train, y_TMPtest = train_test_split(
    fakedata, fakelabels, train_size=partitons[0], random_state=42)
split=partitons[1]/np.sum(partitons[1:])
X_devset, X_test, y_devset, y_test = train_test_split(
    X_TMPtest, y_TMPtest, train_size=split, random_state=42)



In [7]:
print(f'training data size: {X_train.shape}')
print(f'devset data size: {X_devset.shape}')
print(f'test data size: {X_test.shape}')


training data size: (8, 4)
devset data size: (1, 4)
test data size: (1, 4)


In [12]:
partitons=np.array(partitons)
partitonBnd=np.cumsum(partitons*len(fakelabels)).astype(int)
randidx=np.random.permutation(range(len(fakelabels)))
randidx

array([8, 1, 4, 3, 7, 5, 6, 0, 2, 9])

In [11]:
partitonBnd

array([ 8,  9, 10])

In [16]:
X_train=fakedata[randidx[:partitonBnd[0]],:]
y_train=fakelabels[randidx[:partitonBnd[0]]]
print(X_train)
print()
print(y_train)

[[91 92 93 94]
 [21 22 23 24]
 [51 52 53 54]
 [41 42 43 44]
 [81 82 83 84]
 [61 62 63 64]
 [71 72 73 74]
 [11 12 13 14]]

[ True False False False  True  True  True False]


In [20]:
X_devset=fakedata[randidx[partitonBnd[0]:partitonBnd[1]],:]
y_devset=fakelabels[randidx[partitonBnd[0]:partitonBnd[1]]]
print(X_devset)
print()
print(y_devset)

[[31 32 33 34]]

[False]


In [22]:
X_test=fakedata[randidx[partitonBnd[1]:partitonBnd[2]],:]
y_test=fakelabels[randidx[partitonBnd[1]:partitonBnd[2]]]
print(X_test)
print()
print(y_test)

[[101 102 103 104]]

[ True]
