In [1]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
widenet=nn.Sequential(nn.Linear(2,4),
                     nn.Linear(4,3),)
deepnet=nn.Sequential(nn.Linear(2,2),
                     nn.Linear(2,2),
                     nn.Linear(2,3),)
print(widenet)
print()
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [6]:
for p in deepnet.named_parameters():
    print(p)
    print()
    print(len(p[1]))
    print()

('0.weight', Parameter containing:
tensor([[-0.3271, -0.3949],
        [-0.0846, -0.6919]], requires_grad=True))

2

('0.bias', Parameter containing:
tensor([-0.5105,  0.1837], requires_grad=True))

2

('1.weight', Parameter containing:
tensor([[ 0.4009,  0.2847],
        [-0.6736,  0.3906]], requires_grad=True))

2

('1.bias', Parameter containing:
tensor([ 0.3765, -0.2498], requires_grad=True))

2

('2.weight', Parameter containing:
tensor([[-0.5827, -0.2275],
        [ 0.1349,  0.6969],
        [ 0.4130,  0.0044]], requires_grad=True))

3

('2.bias', Parameter containing:
tensor([0.4008, 0.1127, 0.3227], requires_grad=True))

3



In [8]:
numNodesInWide=0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide+=len(p[1])
numNodesInDeep=0
for paramName,paramVect in deepnet.named_parameters():
     if 'bias' in paramName:
            numNodesInDeep+=len(paramVect)
print(f'there are {numNodesInWide} nodes in the wide network')
print(f'there are {numNodesInDeep} nodes in the deep network')


there are 7 nodes in the wide network
there are 7 nodes in the deep network


In [9]:
for p in widenet.parameters():
    print(p)
    print()

Parameter containing:
tensor([[-0.7044, -0.2381],
        [-0.2941, -0.2944],
        [-0.1212,  0.0758],
        [-0.4099, -0.0066]], requires_grad=True)

Parameter containing:
tensor([ 0.2191, -0.4090, -0.3948, -0.3411], requires_grad=True)

Parameter containing:
tensor([[-0.2954, -0.2461,  0.4083,  0.1192],
        [-0.1637, -0.1634,  0.3091, -0.4683],
        [-0.0078,  0.2343,  0.2519, -0.2452]], requires_grad=True)

Parameter containing:
tensor([0.1701, 0.1438, 0.4602], requires_grad=True)



In [11]:
nparams=0
for p in widenet.parameters():
    if p.requires_grad:
        print(f'this piece has {p.numel()} parameters')
        nparams+=p.numel()
print(f'total of {nparams} parameters')

this piece has 8 parameters
this piece has 4 parameters
this piece has 12 parameters
this piece has 3 parameters
total of 27 parameters


In [12]:
nparams=np.sum([p.numel() for p in widenet.parameters() if p.requires_grad])
print(f'Widenet has {nparams} parameters')
nparams=np.sum([p.numel() for p in deepnet.parameters() if p.requires_grad])
print(f'Widenet has {nparams} parameters')


Widenet has 27 parameters
Widenet has 21 parameters


In [15]:
from torchsummary import summary

In [20]:
summary(widenet,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [23]:
summary(deepnet,(2,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 2, 2]               6
            Linear-2                 [-1, 2, 2]               6
            Linear-3                 [-1, 2, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
